import {
  IsNotEmpty,
  IsString,
  IsOptional,
  IsNumber,
  IsUUID,
  IsUrl,
  Min,
  Max,
  MaxLength,
  MinLength,
} from "class-validator";

export class CreateServiceDto {
  // id - it's auto-generated by the database

  @IsNotEmpty()
  @IsUUID()
  user_id: string;

  @IsNotEmpty()
  @IsUUID()
  tag_id: string;

  @IsNotEmpty()
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  title: string;

  @IsOptional()
  @IsUrl() // Validates URL format if media is a URL
  // Or use @IsString() if it's a file path
  media?: string;

  @IsNotEmpty()
  @IsString()
  @MinLength(10)
  @MaxLength(5000)
  content: string;

  @IsOptional() // price has default: 0, so it should be optional
  @IsNumber()
  @Min(0) // Price cannot be negative
  @Max(99999999.99)
  price: number;

  @IsNotEmpty()
  @IsString()
  @MaxLength(255)
  location: string;

  // created - it's auto-generated by @CreateDateColumn
  // updated - it's auto-generated by @UpdateDateColumn
}
