import {
  IsNotEmpty,
  IsString,
  IsOptional,
  IsNumber,
  IsUUID,
  IsUrl,
  Min,
  Max,
  MaxLength,
  MinLength,
  IsIn,
} from "class-validator";

const categories = [
  "art",
  "recording",
  "rehearsal_space",
  "music_lessons",
  "instrument_rental",
  "mixing",
  "mastering",
  "songwriting",
  "music_production",
  "dj_services",
  "band_booking",
  "music_promotion",
  "sheet_music",
  "music_arrangement",
  "studio_musician",
  "audio_editing",
  "voice_over",
  "music_composition",
];

export class CreateServiceDto {
  @IsNotEmpty()
  @IsString()
  @MinLength(3)
  @MaxLength(100)
  title: string;

  @IsOptional()
  @IsUrl() // Validates URL format if media is a URL
  // Or use @IsString() if it's a file path
  media?: string;

  @IsNotEmpty()
  @IsString()
  @MinLength(10)
  @MaxLength(5000)
  content: string;

  @IsOptional() // price has default: 0, so it should be optional
  @IsNumber()
  @Min(0) // Price cannot be negative
  @Max(99999999.99)
  price: number;

  @IsNotEmpty()
  @IsString()
  @MaxLength(255)
  location: string;

  @IsNotEmpty()
  @IsString()
  @MaxLength(100)
  @IsIn(categories)
  category: string;

  // created - it's auto-generated by @CreateDateColumn
  // updated - it's auto-generated by @UpdateDateColumn
}
